# https://taskfile.dev

version: "3"

dotenv:
  - .env

vars:
  DOCKERIMAGES: docker_images
  QCOWIMAGES: qcow_images

tasks:
  default:
    cmds:
      - task -l --sort none
    silent: true

  init:mac:
    desc: Initialize macOS environment
    cmds:
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/packer

  build:
    desc: Build the Packer image with default settings from .env
    cmds:
      - packer build -var='size={{.size}}' -var='region={{.region}}' .
    requires:
      vars:
        - size
        - region

  junos:download:
    desc: Download a Junos vRouter image
    cmds:
      - mkdir -p {{.QCOWIMAGES}}
      - echo "Download the junos vRouter image to the {{.QCOWIMAGES}} directory"
      - cmd: open https://support.juniper.net/support/downloads/?p=vjunos-router
        platforms: [darwin]
      - cmd: echo https://support.juniper.net/support/downloads/?p=vjunos-router
        platforms: [linux, windows]

  junos:convert:
    desc: Convert Junos vRouter image to docker
    cmds:
      - cd {{.QCOWIMAGES}}/ && ls -1 vJunos*.qcow2
      - |
        read -p "Which image do you wish to convert?  " IMAGE
        no_prefix="${IMAGE#vJunos-router-}"
        # Remove suffix
        version="${no_prefix%.qcow2}"

        if [ ! -d vrnetlab ]; then
          git clone https://github.com/hellt/vrnetlab.git
        fi
        mv {{.QCOWIMAGES}}/vJunos*.qcow2 vrnetlab/vjunosrouter/
        cd vrnetlab/vjunosrouter && make
        task VERSION=$version junos:docker:save

  junos:docker:save:
    desc: Save Junos docker image as a tar.gz file
    requires:
      vars:
        - VERSION
    cmds:
      - mkdir -p {{.DOCKERIMAGES}}
      - docker save vrnetlab/juniper_vjunos-router:{{.VERSION}} | gzip > {{.DOCKERIMAGES}}/vjunosrouter_{{.VERSION}}.tar.gz

  tar2targz:
    desc: Convert tar to tar.gz files in the {{.DOCKERIMAGES}} directory
    sources:
      - "{{.DOCKERIMAGES}}/*.tar"
    cmds:
      - for: sources
        cmd: gzip {{.ITEM}}

  arista:download:
    desc: Download an Arista image
    cmds:
      - mkdir -p {{.QCOWIMAGES}}
      - cmd: echo "Download the Arista image to the {{.QCOWIMAGES}} directory"
        silent: true
      - cmd: echo "Select the 'cEOS64' type"
        silent: true
      - cmd: open https://www.arista.com/en/support/software-download
        platforms: [darwin]
        silent: true
      - cmd: echo https://www.arista.com/en/support/software-download
        platforms: [linux, windows]
      - cmd: echo "Run the `task tar2targz` to convert the downloaded .tar to .tar.gz"
        silent: true

  add_ip_to_ssh_config:
    desc: Add the droplet IP to the SSH config file
    silent: true
    cmds:
      - |
        read -p "Enter the droplet IP address: " DROPLETIP
        echo "" >> ~/.ssh/config.d/do
        echo "Host $DROPLETIP" >> ~/.ssh/config.d/do
        echo "    HostName %h" >> ~/.ssh/config.d/do
        echo "    Port 22" >> ~/.ssh/config.d/do
        echo "    User root" >> ~/.ssh/config.d/do
        echo "    # LocalForward 3000 127.0.0.1:3000" >> ~/.ssh/config.d/do
        echo "    # DynamicForward 9999" >> ~/.ssh/config.d/do
        echo "" >> ~/.ssh/config.d/do
        echo "Added $DROPLETIP to ~/.ssh/config.d/do"
        echo "You can now connect using: ssh $DROPLETIP"
    interactive: true
